---
- name: Make monicahq directory.
  file:
    path: "/var/homelabos/monicahq"
    state: directory

- name: Copy monicahq docker-compose.yml file into place.
  template:
    src: docker-compose.monicahq.yml.j2
    dest: /var/homelabos/monicahq/docker-compose.monicahq.yml


- name: Copy monicahq .env file into place.
  template:
    src: monicahq.env.j2
    dest: /var/homelabos/monicahq/monicahq.env
  vars:
    monicahq_db_password: "{{lookup('password', './settings/passwords/monicahq_db_password chars=digits')}}"

- name: Configure monicahq systemd service.
  template:
    src: service.j2
    dest: /etc/systemd/system/monicahq.service

- name: Start monicahq
  systemd:
    name: monicahq
    enabled: "yes"
    daemon-reload: "yes"
    state: started
