---
- debug:
    msg: "Thank you for trying out HomelabOS! We will now provision your server with everything you need."

- debug:
    msg: "Problems? File an issue at https://gitlab.com/NickBusey/HomelabOS/issues"

- apt_repository:
    repo: "{{item}}"
    update_cache: false  # We will do ourselfs afterwards
  with_items:
    - 'deb http://archive.ubuntu.com/ubuntu bionic universe'
    - 'deb-src http://archive.ubuntu.com/ubuntu bionic universe'
    - 'deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable'

- apt:
    update_cache: true

- name: Upgrade all dist packages
  apt: upgrade=dist
  ignore_errors: true
  tags:
    - dependencies

- name: GPG key for the official Docker repository
  apt_key: url=https://download.docker.com/linux/ubuntu/gpg

- name: Install necessities and nice-to-haves
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - git
      - htop
      - iftop
      - iotop
      - mosh
      - screen
      - sudo
      - unattended-upgrades
      - vim
      - zsh
      - docker-ce
      - docker-compose
  tags:
    - dependencies

- name: timezone - configure /etc/timezone
  copy:
    content: "{{ common_timezone | regex_replace('$', '\n') }}"
    dest: /etc/timezone
    owner: root
    group: root
    mode: 0644
  register: common_timezone_config

- name: timezone - Set localtime to UTC
  file: src=/usr/share/zoneinfo/Etc/UTC dest=/etc/localtime
  when: common_timezone_config.changed

- name: timezone - reconfigure tzdata
  command: dpkg-reconfigure --frontend noninteractive tzdata
  when: common_timezone_config.changed

- name: Ensure locale en_US.UTF-8 locale is present
  locale_gen:
    name: en_US.UTF-8
    state: present
...
