---
- name: Install necessities and nice-to-haves
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - cifs-utils
      - curl
      - software-properties-common
      - git
      - htop
      - iftop
      - iotop
      - mosh
      - nfs-common
      - screen
      - sudo
      - unattended-upgrades
      - vim
      - zsh
      - docker
      - docker-compose
      - whois
      - python3
      - python3-pip
      - python3-virtualenv
      - python3-passlib
      - python3-openssl
  tags:
    - dependencies

- name: Install Passlib
  pip:
    name: passlib

- name: timezone - configure /etc/timezone
  copy:
    content: "{{ common_timezone | regex_replace('$', '\n') }}"
    dest: /etc/timezone
    owner: root
    group: root
    mode: 0644
  register: common_timezone_config

- name: timezone - Set localtime to UTC
  file: src=/usr/share/zoneinfo/Etc/UTC dest=/etc/localtime
  when: common_timezone_config.changed

- name: timezone - reconfigure tzdata
  command: dpkg-reconfigure --frontend noninteractive tzdata
  when: common_timezone_config.changed

- name: Ensure locale en_US.UTF-8 locale is present
  locale_gen:
    name: en_US.UTF-8
    state: present

- name: adding existing user '{{ homelab_ssh_user }}' to group docker
  user:
    name: "{{ homelab_ssh_user }}"
    groups: docker
    append: true
  become: true
