# Commented out services are in beta testing and not integrated or documented yet. Uncomment them at your own peril.

version: '3'

services:

  # bitwarden_mssql:
  #   image: bitwarden/mssql:1.16.0
  #   container_name: bitwarden-mssql
  #   restart: always
  #   volumes:
  #     - ../mssql/data:/var/opt/mssql/data
  #     - ../mssql/backups:/etc/bitwarden/mssql/backups
  #   env_file:
  #     - mssql.env
  #     - ../env/mssql.override.env

  # bitwarden_web:
  #   image: bitwarden/web:1.22.0
  #   container_name: bitwarden-web
  #   restart: always
  #   volumes:
  #     - ../web:/etc/bitwarden/web
  #   labels:
  #     traefik.frontend.rule: 'Host:warden.example.com;Path: /'
  #     traefik.enable: 'true'
  #     traefik.port: 80

  # bitwarden_attachments:
  #   image: bitwarden/attachments:1.16.0
  #   container_name: bitwarden-attachments
  #   restart: always
  #   volumes:
  #     - ../core/attachments:/etc/bitwarden/core/attachments
  #   labels:
  #     traefik.frontend.rule: 'Host:warden.example.com;PathPrefix: /attachments'
  #     traefik.enable: 'true'
  #     traefik.port: 80

  # bitwarden_api:
  #   image: bitwarden/api:1.16.0
  #   container_name: bitwarden-api
  #   restart: always
  #   volumes:
  #     - ../core:/etc/bitwarden/core
  #   env_file:
  #     - global.env
  #     - ../env/global.override.env
  #   labels:
  #     traefik.frontend.rule: 'Host: warden.example.com;PathPrefix: /api'
  #     traefik.enable: 'true'
  #     traefik.port: 80

  # bitwarden_identity:
  #   image: bitwarden/identity:1.16.0
  #   container_name: bitwarden-identity
  #   restart: always
  #   volumes:
  #     - ../identity:/etc/bitwarden/identity
  #     - ../core:/etc/bitwarden/core
  #   env_file:
  #     - global.env
  #     - ../env/global.override.env
  #   labels:
  #     traefik.frontend.rule: 'Host: warden.example.com;PathPrefix: /identity'
  #     traefik.enable: 'true'
  #     traefik.port: 80

  # bitwarden_icons:
  #   image: bitwarden/icons:1.16.0
  #   container_name: bitwarden-icons
  #   restart: always
  #   labels:
  #     traefik.frontend.rule: 'Host: warden.example.com;PathPrefix: /icons'
  #     traefik.enable: 'true'
  #     traefik.port: 80

  backups:
    image: lobaro/restic-backup-docker:v1.0
    environment:
      - RESTIC_REPOSITORY={{ s3_path }}
      - AWS_ACCESS_KEY_ID={{ s3_access_code }}
      - AWS_SECRET_ACCESS_KEY={{ s3_secret_code }}
      - RESTIC_PASSWORD={{ s3_backup_password }}
      - BACKUP_CRON={{ s3_backup_cron }}
      - HOSTNAME={{ domain }}
    volumes:
      - /var/homelabos:/data:ro

  convos:
    image: nordaaker/convos
    restart: always
    volumes:
     - /var/homelabos/convos:/data
    ports:
      - 8033:3000
    labels:
      - "traefik.enable=true"
      - "traefik.admin.frontend.rule=Host:irc.{{ domain }}"
      - "traefik.admin.protocol={{ protocol }}"
      - "traefik.admin.port=3000"

  # couchpotato:
  #   image: "couchpotato/couchpotato"
  #   volumes:
  #     - /var/homelabos/couchpotato/data:/datadir
  #     - {{ nas_movies }}:/media
  #   ports:
  #     - "5050:5050"
  #   restart: always
  #   links:
  #     - transmission
  #     - jackett
  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.admin.frontend.rule=Host:couchpotato.{{ domain }}"
  #     - "traefik.admin.protocol={{ protocol }}"
  #     - "traefik.admin.port=5050"

  darksky-influx:
    image: erwinsteffens/darksky-influxdb:latest
    restart: always
    links:
      - influxdb
    environment:
      - DARKSKY_KEY={{ darksky_key }}
      # This is every 2 minutes. This is about as fast as you can go with the free API keys without running out of queries.
      - CRON=0 */2 * * * *
      - INFLUXDB_HOST=influxdb
      - INFLUXDB_DATABASE=darksky
      - DARKSKY_LATITUDE={{ latitude }}
      - DARKSKY_LONGITUDE={{ longitude }}

  dasher:
    image: hijinx/dasher
    restart: always
    network_mode: host
    volumes:
      - /var/homelabos/dasher/config.json:/usr/src/app/config/config.json

  docs:
    image: kyma/docker-nginx
    volumes:
      - /var/homelabos/docs/site:/var/www
    labels:
      - "traefik.enable=true"
      - "traefik.admin.frontend.rule=Host:docs.{{ domain }}"
      - "traefik.admin.protocol={{ protocol }}"
      - "traefik.admin.port=80"

  emby:
    image: emby/embyserver:latest
    restart: always
    volumes:
      - /var/homelabos/emby:/config
      - {{ nas_tv }}:/mnt/tv
      - {{ nas_movies }}:/mnt/movies
    ports:
      - 8096:8096
    labels:
      - "traefik.enable=true"
      - "traefik.admin.frontend.rule=Host:emby.{{ domain }}"
      - "traefik.admin.protocol={{ protocol }}"
      - "traefik.admin.port=8096"

  firefly_iii_app:
    environment:
      - FF_DB_HOST=firefly_iii_db
      - FF_DB_NAME=firefly_db
      - FF_DB_USER=firefly_db
      - FF_DB_PASSWORD=firefly_db_secret
      - FF_APP_KEY=S0m3R@nd0mStr1ngOf31Ch@rsEx@ctly
      - FF_APP_ENV=local
      - TZ={{ timezone }}
      - ServerName=money.{{ domain }}
    image: jc5x/firefly-iii
    links:
      - firefly_iii_db
    ports:
      - "8555:80"
    volumes:
      - /var/homelabos/firefly/export:/var/www/firefly-iii/storage/export
      - /var/homelabos/firefly/upload:/var/www/firefly-iii/storage/upload
    labels:
      - "traefik.enable=true"
      - "traefik.admin.frontend.rule=Host:money.{{ domain }}"
      - "traefik.admin.protocol={{ protocol }}"
      - "traefik.admin.port=80"

  firefly_iii_db:
    environment:
      - MYSQL_DATABASE=firefly_db
      - MYSQL_USER=firefly_db
      - MYSQL_PASSWORD=firefly_db_secret
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    image: "mariadb:latest"
    volumes:
      - "/var/homelabos/firefly/db:/var/lib/mysql"

  # freshrss:
  #   image: linuxserver/freshrss
  #   ports:
  #     - 8084:80
  #   volumes:
  #     - /var/homelabos/freshrss:/config
  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.admin.frontend.rule=Host:rss.{{ domain }}"
  #     - "traefik.admin.protocol={{ protocol }}"
  #     - "traefik.admin.port=80"

  gitea:
    image: gitea/gitea:latest
    environment:
      - USER_UID=1000
      - USER_GID=1000
    restart: always
    links:
      - gitea_db:db
    volumes:
      - ./gitea:/data
    ports:
      - "3030:3000"
      - "222:22"
    depends_on:
      - gitea_db
    labels:
      - "traefik.enable=true"
      - "traefik.admin.frontend.rule=Host:git.{{ domain }}"
      - "traefik.admin.frontend.headers.customFrameOptionsValue=ALLOW-FROM {{ protocol }}://{{ domain }}"
      - "traefik.admin.protocol={{ protocol }}"
      - "traefik.admin.port=3000"

  gitea_db:
    image: mariadb
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=gitea
      - MYSQL_USER=gitea
      - MYSQL_PASSWORD=gitea
      - MYSQL_DATABASE=gitea
    volumes:
      - /var/homelabos/gitea_db:/var/lib/mysql

  grafana:
    image: grafana/grafana
    restart: always
    links:
      - influxdb
    ports:
      - 3000:3000
    volumes:
      - /var/homelabos/grafana:/var/lib/grafana
    environment:
      - GF_INSTALL_PLUGINS=grafana-clock-panel,natel-discrete-panel,petrslavotinek-carpetplot-panel,vonage-status-panel
    labels:
      - "traefik.enable=true"
      - "traefik.admin.frontend.rule=Host:grafana.{{ domain }}"
      - "traefik.admin.protocol={{ protocol }}"
      - "traefik.admin.port=3000"

  homeassistant:
    image: homeassistant/home-assistant
    volumes:
      - /var/homelabos/homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
      - /etc/letsencrypt:/etc/letsencrypt
    restart: always
    ports:
      - 8123:8123
      - 1883:1883
      # - 8080:8080
      - 51827:51827
    links:
      - influxdb
    labels:
      - "traefik.enable=true"
      - "traefik.admin.frontend.rule=Host:homeassistant.{{ domain }}"
      - "traefik.admin.protocol={{ protocol }}"
      - "traefik.admin.port=8123"

  # huginn:
  #   image: huginn/huginn
  #   links:
  #     - huginn_db:mysql
  #   ports:
  #     - 3132:3000
  #   environment:
  #     - HUGINN_DATABASE_NAME=huginn
  #     - HUGINN_DATABASE_USERNAME=huginn
  #     - HUGINN_DATABASE_PASSWORD=somethingsecret
  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.admin.frontend.rule=Host:huginn.{{ domain }}"
  #     - "traefik.admin.protocol={{ protocol }}"
  #     - "traefik.admin.port=3000"

  # huginn_db:
  #   image: mariadb
  #   restart: always
  #   volumes:
  #     - /var/homelabos/huginn_db:/var/lib/mysql
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=huginn
  #     - MYSQL_PASSWORD=somethingsecret
  #     - MYSQL_DATABASE=huginn
  #     - MYSQL_USER=huginn

  influxdb:
    image: influxdb
    restart: always
    volumes:
      - /var/homelabos/influxdb:/var/lib/influxdb
    ports:
      - 8086:8086

  # jackett:
  #   image: linuxserver/jackett
  #   restart: always
  #   volumes: 
  #     - /var/homelabos/jackett/config:/config
  #     - /var/homelabos/jackett/downloads:/downloads
  #     - /etc/localtime:/etc/localtime:ro
  #   environment:
  #     - TZ={{ timezone }}
  #   ports:
  #     - 9117:9117

  nextcloud:
    image: nextcloud
    restart: always
    ports:
      - 8181:80
    links:
      - nextcloud_db
    volumes:
      - /var/homelabos/nextcloud:/var/www/html
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.admin.frontend.rule=Host:nextcloud.{{ domain }}"
      - "traefik.admin.frontend.headers.customFrameOptionsValue=ALLOW-FROM {{ protocol }}://{{ domain }}"
      - "traefik.admin.protocol={{ protocol }}"
      - "traefik.admin.port=80"

  nextcloud_db:
    image: mariadb
    restart: always
    volumes:
      - /var/homelabos/nextcloud_db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=nextcloud
      - MYSQL_PASSWORD=nextcloud
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  # nzbget:
  #   image: linuxserver/nzbget
  #   ports:
  #     - 6789:6789
  #   environment:
  #     - TZ={{ timezone }}
  #   volumes:
  #     - /var/homelabos/nzbget:/config
  #     - {{ nas_downloads }}:/downloads
  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.admin.frontend.rule=Host:nzbget.{{ domain }}"
  #     - "traefik.admin.protocol={{ protocol }}"
  #     - "traefik.admin.port=6789"

  organizr:
    # image: lsiocommunity/organizr
    image: handsomgenious/organizr-v2
    restart: always
    ports:
      - 8083:80
    volumes:
      - /var/homelabos/organizr:/config
    labels:
      - "traefik.enable=true"
      - "traefik.admin.frontend.rule=Host:{{ domain }}"
      - "traefik.admin.protocol={{ protocol }}"
      - "traefik.admin.port=80"

  paperless:
    image: danielquinn/paperless
    restart: always
    ports:
      - "8325:8000"
    healthcheck:
      test: ["CMD", "curl" , "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - /var/homelabos/paperless/data:/usr/src/paperless/data
      - /var/homelabos/paperless/media:/usr/src/paperless/media
    environment:
      - PAPERLESS_OCR_LANGUAGES=
      - PAPERLESS_PASSPHRASE=homelabos
    command: ["runserver", "--insecure", "--noreload", "0.0.0.0:8000"]
    labels:
      - "traefik.enable=true"
      - "traefik.admin.frontend.rule=Host:paperless.{{ domain }}"
      - "traefik.admin.frontend.headers.customFrameOptionsValue=ALLOW-FROM {{ protocol }}://{{ domain }}"
      - "traefik.admin.protocol={{ protocol }}"
      - "traefik.admin.port=8000"

  paperless_consumer:
    image: danielquinn/paperless
    restart: always
    depends_on:
      - paperless
    volumes:
      - /var/homelabos/paperless/data:/usr/src/paperless/data
      - /var/homelabos/paperless/media:/usr/src/paperless/media
      - /mnt/Privatenas/Documents/consume:/consume
      - /mnt/Privatenas/Documents/export:/export
    environment:
      - PAPERLESS_PASSPHRASE=homelabos
    command: ["document_consumer"]

  # pihole:
  #   image: diginc/pi-hole:latest
  #   restart: always
  #   volumes:
  #     - /var/homelabos/pihole/config/:/etc/pihole/
  #     - /var/homelabos/pihole/dnsmasq.d/:/etc/dnsmasq.d/
  #   environment:
  #     - WEBPASSWORD={{ default_password }}
  #     - VIRTUAL_HOST=pihole.{{ domain }}
  #     - ServerIP={{ ansible_ssh_host }}
  #   ports:
  #     - 53:53/tcp
  #     - 53:53/udp
  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.admin.frontend.rule=Host:pihole.{{ domain }}"
  #     - "traefik.admin.protocol={{ protocol }}"
  #     - "traefik.admin.port=80"

  portainer:
    image: portainer/portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/homelabos/portainer:/data
    ports:
      - 9000:9000
    labels:
      - "traefik.enable=true"
      - "traefik.admin.frontend.rule=Host:docker.{{ domain }}"
      - "traefik.admin.protocol={{ protocol }}"
      - "traefik.admin.port=9000"

  # sonarr:
  #   image: linuxserver/sonarr
  #   ports:
  #     - 8989:8989
  #   environment:
  #     - PGID=1000
  #     - PUID=1000
  #     - TZ={{ timezone }}
  #   links:
  #     - jackett
  #     - transmission
  #   volumes:
  #     - /etc/localtime:/etc/localtime:ro
  #     - /var/homelabos/sonarr/config:/config
  #     - {{ nas_tv }}:/tv
  #     - /var/homelabos/sonarr/downloads:/downloads
  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.admin.frontend.rule=Host:sonarr.{{ domain }}"
  #     - "traefik.admin.protocol={{ protocol }}"
  #     - "traefik.admin.port=8989"

  sonerezh:
    image: sonerezh/sonerezh:latest
    links:
      - sonerezh_db:mysql
    volumes:
      - /mnt/music:/music
      - /var/homelabos/sonerezh/thumbnails:/thmubnails
    ports:
      - 8089:80
    environment:
      - SONEREZH_DB_PORT_3306_TCP_ADDR=mysql
      - SONEREZH_DB_ENV_MYSQL_DATABASE=sonerezh
      - SONEREZH_DB_ENV_MYSQL_USER=sonerezh
      - SONEREZH_DB_ENV_MYSQL_PASSWORD=motdepasse
    labels:
      - "traefik.enable=true"
      - "traefik.admin.frontend.rule=Host:music.{{ domain }}"
      - "traefik.admin.protocol={{ protocol }}"
      - "traefik.admin.port=80"

  sonerezh_db:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=motdepasse
      - MYSQL_USER=sonerezh
      - MYSQL_PASSWORD=motdepasse
      - MYSQL_DATABASE=sonerezh
    volumes:
      - /var/homelabos/sonerezh_db:/var/lib/mysql

  telegraf:
    image: telegraf
    restart: always
    volumes:
      - /var/homelabos/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf
      - /var/run/docker.sock:/var/run/docker.sock
    links:
      - influxdb

  terminal:
    image: georgeyord/butterfly-web-terminal
    restart: always
    environment:
      - PASSWORD={{ default_password }}
    ports:
      - 2233:2233
    labels:
      - "traefik.enable=true"
      - "traefik.admin.frontend.rule=Host:terminal.{{ domain }}"
      - "traefik.admin.protocol={{ protocol }}"
      - "traefik.admin.port=2233"

  traefik:
    image: traefik
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/homelabos/traefik/traefik.toml:/etc/traefik/traefik.toml
      - /var/homelabos/traefik/acme.json:/etc/traefik/acme.json

  transmission:
    image: haugene/transmission-openvpn
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    restart: always
    ports:
      - "9091:9091"
      - "8888:8888"
    dns:
      - 8.8.8.8
      - 8.8.4.4
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/homelabos/transmission/data:/data
      - /var/homelabos/transmission/config:/config
      - {{ nas_downloads }}:/downloads
      - /var/homelabos/transmission/watch:/watch
    environment:
      - OPENVPN_PROVIDER=PIA
      - OPENVPN_USERNAME={{ openvpn_username }}
      - OPENVPN_PASSWORD={{ openvpn_password }}
      - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
      - PGID=1000
      - PUID=1000
      - TZ={{ timezone }}
      - TRANSMISSION_RPC_AUTHENTICATION_REQUIRED=true
      # Password = `transmission`
      - TRANSMISSION_RPC_PASSWORD="{62b16db87b89a91dd49a5110a7cafc06d20eb4f2wtK6kqPj"
      - TRANSMISSION_RPC_USERNAME={{ default_username }}
    labels:
      - "traefik.enable=true"
      - "traefik.admin.frontend.rule=Host:torrent.{{ domain }}"
      - "traefik.admin.protocol={{ protocol }}"
      - "traefik.admin.port=9091"
  
  # urbackup:
  #   image: cfstras/urbackup
  #   ports:
  #     - 55413
  #     - 55414
  #     - 55415
  #     - 35622
  #   volumes:
  #     - /etc/localtime:/etc/localtime:ro
  #     - /var/homelabos/urbackup/db/:/var/urbackup
  #     - {{ nas_backups }}:/backup:rw
  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.admin.frontend.rule=Host:backup.{{ domain }}"
  #     - "traefik.admin.protocol={{ protocol }}"
  #     - "traefik.admin.port=55414"