---
- name: Make paperless directory.
  file:
    path: "/var/homelabos/paperless"
    state: directory

- name: Copy paperless docker-compose.yml file into place.
  template:
    src: docker-compose.paperless.yml.j2
    dest: /var/homelabos/paperless/docker-compose.paperless.yml
  vars:
    tor_domain: "{{ tor_http_domain_file.stdout }}"

- name: Configure paperless systemd service.
  template: src=paperless.service dest=/etc/systemd/system/paperless.service

- name: Start paperless
  systemd:
    name: paperless
    enabled: "yes"
    daemon-reload: "yes"
    state: started
...
