---
- name: Make jellyfin directory.
  file:
    path: "{{ volumes_root }}/jellyfin"
    state: directory

- name: Copy jellyfin docker-compose.yml file into place.
  template:
    src: docker-compose.jellyfin.yml.j2
    dest: "{{ volumes_root }}/jellyfin/docker-compose.yml"
  vars:
    tor_domain: "{{ tor_http_domain_file.stdout | default('') }}"

- name: Configure jellyfin systemd service.
  template:
    src: service.j2
    dest: /etc/systemd/system/jellyfin.service

- name: Start jellyfin
  systemd:
    name: jellyfin
    enabled: "yes"
    daemon-reload: "yes"
    state: started
