---
- name: Make grownetics directory.
  file:
    path: "{{ item }}"
    state: directory
    mode: 0777
  loop:
    - "{{ volumes_root }}/grownetics"

- name: Copy grownetics .env file into place.
  template:
    src: env.j2
    dest: "{{ volumes_root }}/grownetics/.env"

- name: Copy grownetics docker-compose.yml file into place.
  template:
    src: docker-compose.grownetics.yml.j2
    dest: "{{ volumes_root }}/grownetics/docker-compose.grownetics.yml"
  vars:
    tor_domain: "{{ tor_http_domain_file.stdout | default('') }}"

- name: Configure grownetics systemd service.
  template:
    src: service.j2
    dest: /etc/systemd/system/grownetics.service

- name: Start grownetics
  systemd:
    name: grownetics
    enabled: "yes"
    daemon-reload: "yes"
    state: started
