---
site_name: HomelabOS
site_url: https://homelabos.com/docs/
repo_name: NickBusey/HomelabOS
repo_url: https://gitlab.com/NickBusey/HomelabOS
edit_uri: "/NickBusey/HomelabOS/edit/dev/docs"
markdown_extensions:
  - admonition
  - pymdownx.details
  - toc:
      permalink: true
theme:
  name: material
  palette:
    primary: orange
  icon:
    logo: material/home
  features:
    - instant
nav:
  - Home: index.md
  - Introduction: setup/introduction.md
  - Installation: setup/installation.md
  - Getting Started: setup/gettingstarted.md
  - Troubleshooting / FAQ: setup/faq.md
  - Setup:
      - Backups: setup/backups.md
      - Bastion Server: setup/bastion.md
      - Email: setup/email.md
      - Traefik: setup/traefik.md
      - Terraform: setup/terraform.md
      - Tor Onion Services: setup/tor.md
      - VPN Setup: setup/vpn.md
  - Included Software:
      - Analytics:
          - Matomo: software/matomo.md
      - Automation:
          - Home Assistant: software/homeassistant.md
          - HomeBridge: software/homebridge.md
          - Kibitzr: software/kibitzr.md
          - n8n: software/n8n.md
          - NodeRED: software/nodered.md
      - Blogging Platforms:
          - Ghost: software/ghost.md
      - Calendaring and Contacts Management:
          - NextCloud: software/nextcloud.md
      - Chat:
          - The Lounge: software/thelounge.md
          - Zulip: software/zulip.md
      - Document Management:
          - Mayan: software/mayan.md
          - Paperless: software/paperless.md
      - E-books:
          - Calibre: software/calibre.md
      - Email:
          - Mailserver: software/mailserver.md
          - Mailu: software/mailu.md
      - Federated Identity/Authentication:
          - Authelia: software/authelia.md
          - OpenLDAP: software/openldap.md
      - Feed Readers:
          - FreshRSS: software/freshrss.md
          - Miniflux: software/miniflux.md
      - File Sharing and Synchronization:
          - Duplicati: software/duplicati.md
          - Jackett: software/jackett.md
          - Lidarr: software/lidarr.md
          - Minio: software/minio.md
          - Mylar: software/mylar.md
          - Ombi: software/ombi.md
          - qBittorrent: software/qbittorrent.md
          - Radarr / Sonarr: software/radarr-sonarr.md
          - SickChill: software/sickchill.md
          - Synchthing: software/syncthing.md
          - Transmission: software/transmission.md
      - Games:
          - Factorio: software/factorio.md
          - Minecraft: software/minecraft.md
          - MinecraftBedrockServer: software/minecraftbedrockserver.md
          - MassiveDecks: software/massivedecks.md
      - Gateways and terminal sharing:
          - Guacamole: software/guacamole.md
          - WebVirtMgr: software/webvirtmgr.md
      - Media Streaming:
          - Airsonic: software/airsonic.md
          - Beets: software/beets.md
          - Emby: software/emby.md
          - Jellyfin: software/jellyfin.md
          - Mstream: software/mstream.md
          - Plex: software/plex.md
          - Funkwhale: software/funkwhale.md
      - Misc/Other:
          - Chowdown: software/chowdown.md
          - Darksky: software/darksky.md
          - Dasher: software/dasher.md
          - ERPNext: software/erpnext.md
          - Folding@home: software/folding_at_home.md
          - Gotify: software/gotify.md
          - Grocy: software/grocy.md
          - Grownetics: software/grownetics.md
          - Inventario: software/inventario.md
          - Mashio: software/mashio.md
          - Monica: software/monica.md
          - Pi-hole: software/pihole.md
          - Poli: software/poli.md
          - Portainer: software/portainer.md
          - PrivateBin: software/privatebin.md
          - Sabnzbd: software/sabnzbd.md
          - Searx: software/searx.md
          - Ubooquity: software/ubooquity.md
          - Watchtower: software/watchtower.md
          - BarcodeBuddy: software/barcodebuddy.md
      - Money, Budgeting and Management:
          - Firefly III: software/firefly.md
      - Monitoring:
          - Grafana: software/grafana.md
          - HealthChecks: software/healthchecks.md
          - Huginn: software/huginn.md
          - Netdata: software/netdata.md
          - Speedtest: software/speedtest.md
          - Tautulli: software/tautulli.md
          - TICK: software/tick.md
      - Note-taking and Editors:
          - BulletNotes: software/bulletnotes.md
          - Trilium: software/trilium.md
      - Password Managers:
          - Bitwarden: software/bitwarden.md
      - Personal Dashboards:
          - Heimdall: software/heimdall.md
          - Homedash: software/homedash.md
          - Organizr: software/organizr.md
      - Photo and Video Galleries:
          - Digikam: software/digikam.md
          - OwnPhotos: software/ownphotos.md
          - PhotoPrism: software/photoprism.md
          - Piwigo: software/piwigo.md
          - Pixelfed: software/pixelfed.md
      - Read it Later Lists:
          - Wallabag: software/wallabag.md
      - Software Development:
          - Codeserver: software/codeserver.md
          - Drone: software/drone.md
          - Gitea: software/gitea.md
          - Gitlab: software/gitlab.md
          - Snibox: software/snibox.md
      - Task management/To-do lists:
          - Wekan: software/wekan.md
      - VPN:
          - OpenVPN: software/openvpn.md
      - Webservers:
          - Apache2: software/apache2.md
      - Wikis:
          - Bookstack: software/bookstack.md
          - Tiddlywiki: software/tiddlywiki.md
  - Development:
      - Adding Services: development/adding_services.md
      - Contributing: development/contributing.md
      - Migrations: development/migrations.md
      - Vagrant: development/vagrant.md
