---
site_name: HomelabOS
repo_url: https://gitlab.com/NickBusey/HomelabOS
edit_uri: edit/master/docs
theme:
  name: material
  logo:
    icon: home
nav:
  - Home: index.md
  - Installation: setup/installation.md
  - Getting Started: setup/gettingstarted.md
  - Setup:
      - Backups: setup/backups.md
      - Bastion: setup/bastion.md
      - Email: setup/email.md
      - Traefik: setup/traefik.md
      - Terraform: setup/terraform.md
      - Tor Onion Services: setup/tor.md
      - VPN Setup: setup/vpn.md
  - Included Software:
      - Airsonic: software/airsonic.md
      - Apache2: software/apache2.md
      - Apple Health: software/applehealth.md
      - Authelia: software/authelia.md
      - Beets: software/beets.md
      - Bitwarden: software/bitwarden.md
      - BulletNotes: software/bulletnotes.md
      - Calibre: software/calibre.md
      - Darksky: software/darksky.md
      - Dasher: software/dasher.md
      - Digikam: software/digikam.md
      - Duplicati: software/duplicati.md
      - Emby: software/emby.md
      - Drone: software/drone.md
      - Emby: software/emby.md
      - Firefly III: software/firefly.md
      - FreshRSS: software/freshrss.md
      - Ghost: software/ghost.md
      - Gitea: software/gitea.md
      - Grafana: software/grafana.md
      - Guacamole: software/guacamole.md
      - Home Assistant: software/homeassistant.md
      - HomeBridge: software/homebridge.md
      - Inventario: software/inventario.md
      - Jackett: software/jackett.md
      - Jellyfin: software/jellyfin.md
      - Kibitzr: software/kibitzr.md
      - Lidarr: software/lidarr.md
      - Mailserver: software/mailserver.md
      - Mashio: software/mashio.md
      - Matomo: software/matomo.md
      - Mayan: software/mayan.md
      - Miniflux: software/miniflux.md
      - Minio: software/minio.md
      - Monica: software/monica.md
      - Mylar: software/mylar.md
      - Netdata: software/netdata.md
      - NextCloud: software/nextcloud.md
      - Ombi: software/ombi.md
      - OwnPhotos: software/ownphotos.md
      - Paperless: software/paperless.md
      - Pi-hole: software/pihole.md
      - Piwigo: software/piwigo.md
      - Pixelfed: software/pixelfed.md
      - Plex: software/plex.md
      - Portainer: software/portainer.md
      - Radarr / Sonarr: software/radarr-sonarr.md
      - SickChill: software/sickchill.md
      - Synchthing: software/syncthing.md
      - Tautulli: software/tautulli.md
      - The Lounge: software/thelounge.md
      - TICK: software/tick.md
      - Transmission: software/transmission.md
      - Trilium: software/trilium.md
      - Wallabag: software/wallabag.md
      - WebVirtMgr: software/webvirtmgr.md
      - Wekan: software/wekan.md
      - Watchtower: software/watchtower.md
      - Zulip: software/zulip.md
  - Development:
      - Adding Services: development/adding_services.md
      - Contributing: development/contributing.md
      - Migrations: development/migrations.md
