---
site_name: HomelabOS
site_url: https://homelabos.com/docs/
repo_name: NickBusey/HomelabOS
repo_url: https://gitlab.com/NickBusey/HomelabOS
edit_uri: "/NickBusey/HomelabOS/edit/dev/docs"
plugins:
  - search # necessary for search to work
  - git-revision-date-localized
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - toc:
      permalink: true
theme:
  name: material
  palette:
    primary: orange
  icon:
    logo: material/home
  features:
    - instant
nav:
  - Home: index.md
  - Introduction: setup/introduction.md
  - Installation: setup/installation.md
  - Getting Started: setup/gettingstarted.md
  - Troubleshooting / FAQ: setup/faq.md
  - Setup:
      - Backups: setup/backups.md
      - Bastion Server: setup/bastion.md
      - Email: setup/email.md
      - Storage: setup/storage.md
      - Traefik: setup/traefik.md
      - Terraform: setup/terraform.md
      - Tor Onion Services: setup/tor.md
      - VPN Setup: setup/vpn.md
  - Included Software:
    - Analytics:
      - Matomo: software/matomo.md
    - Automation:
      - Home Assistant: software/homeassistant.md
      - HomeBridge: software/homebridge.md
      - Kibitzr: software/kibitzr.md
    - Blogging Platforms:
      - Ghost: software/ghost.md
    - Calendaring and Contacts Management:
      - NextCloud: software/nextcloud.md
    - Chat:
      - Matterbridge: software/matterbridge.md
      - The Lounge: software/thelounge.md
      - Zulip: software/zulip.md
    - Docker & VM Management:
      - Portainer: software/portainer.md
      - Taisun: software/taisun.md
    - Document Management:
      - Mayan EDMS: software/mayan.md
      - Paperless: software/paperless.md
      - Teedy: software/teedy.md
    - E-books:
      - Calibre: software/calibre.md
      - Lazylibrarian: software/lazylibrarian.md
    - Email:
      - Mailu: software/mailu.md
    - Federated Identity/Authentication:
      - Authelia: software/authelia.md
      - Keycloak: software/keycloak.md
      - OpenLDAP: software/openldap.md
    - Feed Readers:
      - FreshRSS: software/freshrss.md
      - Miniflux: software/miniflux.md
    - File Sharing and Synchronization:
      - Duplicati: software/duplicati.md
      - Jackett: software/jackett.md
      - Lidarr: software/lidarr.md
      - Minio: software/minio.md
      - Mylar: software/mylar.md
      - Ombi: software/ombi.md
      - qBittorrent: software/qbittorrent.md
      - Radarr: software/radarr-sonarr.md
      - Samba: software/samba.md
      - SickChill: software/sickchill.md
      - Sonarr: software/radarr-sonarr.md
      - Syncthing: software/syncthing.md
      - Transmission: software/transmission.md
      - WebDAV: software/webdavserver.md
      - Xteve: software/xteve.md
    - Games:
      - Factorio: software/factorio.md
      - Minecraft: software/minecraft.md
      - MinecraftBedrockServer: software/minecraftbedrockserver.md
      - QuakeJS: software/quakejs.md
    - Gateways and terminal sharing:
      - Guacamole: software/guacamole.md
      - WebVirtMgr: software/webvirtmgr.md
    - Media Streaming:
      - Airsonic: software/airsonic.md
      - Beets: software/beets.md
      - Emby: software/emby.md
      - Funkwhale: software/funkwhale.md
      - Jellyfin: software/jellyfin.md
      - Massive Decks: software/massivedecks.md
      - mStream: software/mstream.md
      - PeerTube: software/peertube.md
      - Plex: software/plex.md
    - Misc/Other:
      - AdGuard Home: software/adguardhome.md
      - Barcode Buddy: software/barcodebuddy.md
      - Chowdown: software/chowdown.md
      - Cockpit: software/system-cockpit.md
      - CodiMD: software/codimd.md
      - Darksky: software/darksky.md
      - Dasher: software/dasher.md
      - DuckDNS: software/duckdns.md
      - EtherCalc: software/ethercalc.md
      - ERPNext: software/erpnext.md
      - Folding@home: software/folding_at_home.md
      - Gotify: software/gotify.md
      - Grocy: software/grocy.md
      - Grownetics: software/grownetics.md
      - Hubzilla: software/hubzilla.md
      - Inventario: software/inventario.md
      - Invidious: software/invidious.md
      - InvoiceNinja: software/invoiceninja.md
      - Mashio: software/mashio.md
      - Mealie: software/mealie.md
      - Monica: software/monica.md
      - n8n: software/n8n.md
      - NodeRED: software/nodered.md
      - OctoPrint: software/octoprint.md
      - Pi-hole: software/pihole.md
      - Poli: software/poli.md
      - PrivateBin: software/privatebin.md
      - RSSHub: software/rsshub.md
      - Sabnzbd: software/sabnzbd.md
      - Searx: software/searx.md
      - Shinobi: software/shinobi.md
      - Simply-Shorten: software/simplyshorten.md
      - The Spaghetti Detective: software/thespaghettidetective.md
      - Ubooquity: software/ubooquity.md
      - UnifiController: software/unificontroller.md
      - Watchtower: software/watchtower.md
      - WebTrees: software/webtrees.md
      - Zammad: software/zammad.md
    - Money, Budgeting and Management:
      - Firefly III: software/firefly.md
    - Monitoring:
      - ELK Stack: software/elkstack.md
      - Grafana: software/grafana.md
      - HealthChecks: software/healthchecks.md
      - Huginn: software/huginn.md
      - Netdata: software/netdata.md
      - Speedtest: software/speedtest.md
      - Speedtest Tracker: software/speedtest_tracker.md
      - Statping: software/statping.md
      - Tautulli: software/tautulli.md
      - TICK: software/tick.md
    - Note-taking and Editors:
      - BulletNotes: software/bulletnotes.md
      - Trilium: software/trilium.md
      - Turtl: software/turtl.md
    - Password Managers:
      - Bitwarden: software/bitwarden.md
    - Personal Dashboards:
      - Heimdall: software/heimdall.md
      - Homedash: software/homedash.md
      - Organizr: software/organizr.md
      - SUI: software/sui.md
    - Photo and Video Galleries:
      - Digikam: software/digikam.md
      - OwnPhotos: software/ownphotos.md
      - PhotoPrism: software/photoprism.md
      - Piwigo: software/piwigo.md
      - Pixelfed: software/pixelfed.md
    - Read it Later Lists:
      - Wallabag: software/wallabag.md
    - Social Networking:
      - Pleroma: software/pleroma.md
    - Software Development:
      - code-server: software/codeserver.md
      - Drone: software/drone.md
      - Gitea: software/gitea.md
      - GitLab: software/gitlab.md
      - Jenkins: software/jenkins.md
      - Snibox: software/snibox.md
    - Task management/To-do lists:
      - Wekan: software/wekan.md
    - VPN:
      - OpenVPN: software/openvpn.md
    - Web servers:
      - Apache2: software/apache2.md
    - Wikis:
      - BookStack: software/bookstack.md
      - TiddlyWiki: software/tiddlywiki.md
  - Development:
      - Adding Services: development/adding_services.md
      - Contributing: development/contributing.md
      - Migrations: development/migrations.md
      - Vagrant: development/vagrant.md
