---
- hosts: 127.0.0.1
  connection: local
  vars_prompt:
    - name: homelab_ip
      prompt: "What is the IP of your server that you can SSH to?"
      private: "False"

    - name: homelab_ssh_user
      prompt: "What is the user you can SSH to your homelab server with?"
      private: "False"

    - name: ansible_become_password
      prompt: "What is the password the above user needs for sudo access? (Press return if none.)"

    - name: default_username
      prompt: "What is the default username you would like created as an admin on the various HomelabOS services?"
      private: "False"

    - name: default_password
      prompt: "What is the default password you would like for this account?"

    - name: domain
      prompt: "What is the domain you have pointed at your Homelab server with ports 80 and 443?"
      private: "False"

    - name: admin_email
      prompt: "What is a current valid email address for the admin? (Required for HTTPS via LetsEncrypt)"
      private: "False"

  roles:
    - homelabos_config
...
