---
# Initial setup so Ansible can actually work.
- name: Install python (required by Ansible).
  gather_facts: "False"
  hosts: all
  become: "True"
  become_method: sudo
  pre_tasks:
    - name: 'Update Apt Cache'
      raw: sudo apt-get update
      ignore_errors: true
    - name: 'Install Python'
      raw: sudo apt-get -y install python-simplejson

# Configure a TOR hidden service for remote access without a public IP
- name: "Setup TOR"
  tags: tinc
  hosts: all
  become: true
  become_method: sudo
  roles:
    - role: tor
      when: enable_tor

# Configure the server itself
- hosts: all
  become: true
  gather_facts: "True"
  tags: common
  roles:
    # Install Docker, configure basic server settings
    - homelabos_common

- name: "Setup tinc VPN"
  tags: tinc
  hosts: all
  become: true
  become_method: sudo
  roles:
    - role: homelabos_tinc
      when: enable_tinc

- name: "Update Tinc Bastion Host with iptables rules"
  hosts: tinc
  become: true
  become_method: sudo
  tags: tinc-iptables
  roles:
    - role: homelabos_tinc_iptables
      when: enable_tinc

# Install and configure HomelabOS services
- hosts: homelabos
  become: true
  gather_facts: "True"
  tags:
    - homelabos
    - deploy
  roles:
    - homelabos_deploy

...
