---

- hosts: all
  become: "True"

  tasks:
    - name: Restart services
      systemd:
        name: "{{ service_item }}"
        state: restarted
        enabled: true
      when: "query"
      loop: "{{ services | flatten(1) }}"
      loop_control:
        loop_var: service_item
      ignore_errors: "yes"
      vars:
        query: "{{ service_item + '.enable' }}"
