---
- name: Make HomelabOS data directories.
  file:
    path: "{{ item }}"
    state: directory
    mode: '1777'
  loop:
    - /var/homelabos/apple_health_influx
    - /var/homelabos/dasher
    - /var/homelabos/docker
    - /var/homelabos/telegraf
    - /var/homelabos/traefik
    - /var/homelabos/grafana/data
    - /var/homelabos/grafana/datasources
    - /var/homelabos/grafana/dashboards
    - /mnt/nas
  ignore_errors: "yes"

- name: Configure Docker.
  template: src={{ item }} dest=/var/homelabos/docker/
  loop:
    - .env
    - monica.env

- name: Configure Telegraf.
  template: src=telegraf.conf dest=/var/homelabos/telegraf/telegraf.conf

- name: Configure Traefik.
  template: src=traefik.toml dest=/var/homelabos/traefik/traefik.toml

- name: Configure SSL
  file:
    path: /var/homelabos/traefik/acme.json
    mode: 0600
    state: touch

- name: Configure Dasher
  template: src=dasher.config.json dest=/var/homelabos/dasher/config.json

- name: Configure Apple Health Importer
  template: src=apple_health_config.yml dest=/var/homelabos/apple_health_influx/config.yml

- name: Configure NAS
  lineinfile:
    path: /etc/fstab
    line: '{{ nas_path }}  /mnt/nas  cifs  username={{ nas_user }},vers=2.0,dom={{ nas_workgroup }},password={{ nas_pass }},uid=1000,iocharset=utf8,file_mode=0777,dir_mode=0777  0  0'

- name: Configure Grafana Datasources
  template: src={{ item }} dest=/var/homelabos/grafana/datasources/{{ item }}
  loop:
    - grafana.datasource.influxdb.yaml

- name: Configure Grafana Dashboards
  template: src={{ item }} dest=/var/homelabos/grafana/dashboards/{{ item }}
  loop:
    - grafana.dashboards.yaml
    - grafana.dash.homelab.json

- name: Mount NAS Drives
  command: mount -a
  args:
    warn: "no"
  ignore_errors: "yes"

- name: Configure HomelabOS systemd service.
  template: src=homelabos.service dest=/etc/systemd/system/homelabos.service

- name: Read Tor connection info
  shell: cat /var/lib/tor/http-onion/hostname
  register: tor_http_domain_file

- name: Copy HomelabOS docker-compose.yml file into place.
  template:
    src: docker-compose.yml
    dest: /var/homelabos/docker/docker-compose.yml
  vars:
    tor_domain: "{{ tor_http_domain_file.stdout }}"

- name: Create HomelabOS hosts file.
  file:
    path: /var/homelabos/homelab_hosts
    state: touch

- name: Configure HomelabOS hosts file. You can find it at /var/homelabos/homelab_hosts on your server.
  lineinfile:
    path: /var/homelabos/homelab_hosts
    line: '{{ ansible_host }} {{ item }}.{{ domain }} {{ item }}'
  with_items:
    - "{{ services }}"

- name: Pull latest HomelabOS service docker images. (This could take a while the first time, it has to download quite a bit.)
  command: docker-compose -f /var/homelabos/docker/docker-compose.yml pull

# - name: Disable resolved service to make room for pihole
#   systemd:
#     name: systemd-resolved
#     state: stopped
#     enabled: no
#     daemon-reload: yes

# - name: Configure resolve.conf to use localhost
#   lineinfile:
#     path: /etc/resolv.conf
#     line: 'nameserver 127.0.0.1'

- name: Restart HomelabOS service.
  systemd:
    name: homelabos
    enabled: "yes"
    daemon-reload: "yes"
    state: restarted

- name: Read Tor SSH connection info
  shell: cat /var/lib/tor/ssh-onion/hostname
  register: tor_ssh_domain_file

- debug:
    msg: "HomelabOS Installed successfully! Go to https://{{ domain }}/ to get started. You can also access your services via Tor at http://{{ tor_http_domain_file.stdout }}/ Finally you can SSH to {{ tor_ssh_domain_file.stdout }}"

- debug:
    msg: "Problems? File an issue at https://gitlab.com/NickBusey/HomelabOS/issues"
...
