---
- name: Make webdavserver directory.
  file:
    path: "{{ volumes_root }}/webdavserver"
    state: directory

- name: Copy webdavserver docker-compose.yml file into place.
  template:
    src: docker-compose.webdavserver.yml.j2
    dest: "{{ volumes_root }}/webdavserver/docker-compose.webdavserver.yml"
  vars:
    tor_domain: "{{ tor_http_domain_file.stdout | default('') }}"

- name: Configure webdavserver systemd service.
  template:
    src: service.j2
    dest: /etc/systemd/system/webdavserver.service

- name: Start webdavserver
  systemd:
    name: webdavserver
    enabled: "yes"
    daemon-reload: "yes"
    state: started
