---
- name: Make ghost directory.
  file:
    path: "/var/homelabos/ghost"
    state: directory

- name: Copy ghost docker-compose.yml file into place.
  template:
    src: docker-compose.ghost.yml.j2
    dest: /var/homelabos/ghost/docker-compose.ghost.yml
  vars:
    tor_domain: "{{ tor_http_domain_file.stdout if tor_http_domain is defined else '' }}"

- name: Configure ghost systemd service.
  template: src=service.j2 dest=/etc/systemd/system/ghost.service

- name: Start ghost
  systemd:
    name: ghost
    enabled: "yes"
    daemon-reload: "yes"
    state: started
...
