---
- name: Make authelia directory.
  file:
    path: "{{ volumes_root }}/authelia"
    state: directory

- name: Copy authelia docker-compose.yml file into place.
  template:
    src: docker-compose.authelia.yml.j2
    dest: "{{ volumes_root }}/authelia/docker-compose.authelia.yml"
  vars:
    tor_domain: "{{ tor_http_domain_file.stdout | default('') }}"

- name: Generate new slapd compatible password.
  shell: >
    mkpasswd --rounds 500000 -m sha-512 --salt `head -c 40 /dev/random |
    base64 |
    sed -e 's/+/./g' |
    cut -b 10-25` '{{default_password}}'
  register: slappasswd_out
  become: false

- name: Copy userdb.yml file into place.
  template:
    src: userdb.yml.j2
    dest: "{{ volumes_root }}/authelia/userdb.yml"
  vars:
    slapd_password: "{{ slappasswd_out.stdout }}"

- name: Copy authelia_config.yml file into place.
  template:
    src: authelia_config.yml.j2
    dest: "{{ volumes_root }}/authelia/authelia_config.yml"
  vars:
    domain_parts: "{{ domain.split('.') }}"

- name: Configure authelia systemd service.
  template:
    src: service.j2
    dest: /etc/systemd/system/authelia.service

- name: Start authelia
  systemd:
    name: authelia
    enabled: "yes"
    daemon-reload: "yes"
    state: started
