---
- name: Make mashio directory.
  file:
    path: "{{ volumes_root }}/mashio"
    state: directory

- name: Copy mashio docker-compose.yml file into place.
  template:
    src: docker-compose.mashio.yml.j2
    dest: "{{ volumes_root }}/mashio/docker-compose.mashio.yml"


- name: Configure mashio systemd service.
  template:
    src: service.j2
    dest: /etc/systemd/system/mashio.service

- name: Start mashio
  systemd:
    name: mashio
    enabled: "yes"
    daemon-reload: "yes"
    state: started
