---
- name: Make matomo directory.
  file:
    path: "{{ volumes_root }}/matomo"
    state: directory

- name: Copy matomo docker-compose.yml file into place.
  template:
    src: docker-compose.matomo.yml.j2
    dest: "{{ volumes_root }}/matomo/docker-compose.matomo.yml"
  vars:
    tor_domain: "{{ tor_http_domain_file.stdout | default('') }}"

- name: Configure matomo systemd service.
  template:
    src: service.j2
    dest: /etc/systemd/system/matomo.service

- name: Start matomo
  systemd:
    name: matomo
    enabled: "yes"
    daemon-reload: "yes"
    state: started
