---
- name: Make mayan directory.
  file:
    path: "{{ volumes_root }}/mayan"
    state: directory

- name: Copy mayan docker-compose.yml file into place.
  template:
    src: docker-compose.mayan.yml.j2
    dest: "{{ volumes_root }}/mayan/docker-compose.yml"
  vars:
    tor_domain: "{{ tor_http_domain_file.stdout | default('') }}"

- name: Configure mayan systemd service.
  template:
    src: service.j2
    dest: /etc/systemd/system/mayan.service

- name: Start mayan
  systemd:
    name: mayan
    enabled: "yes"
    daemon-reload: "yes"
    state: started
