---

- name: Tor Password
  tor_password:
    password: "{{ tor_control_password }}"
    password_hash: "{{ tor_stored_hash | default(omit)}}"
  no_log: False
  register: tor_password
  when: tor_control_password is defined

- debug: msg={{ tor_password }}

## Store password
- set_fact:
    tor_persistence:
      tor_hashed_password: "{{ tor_password['password_hash'] }}"
  when: tor_control_password is defined

## Hack as long We can't read torrc
- name: persist_password hash
  template:
    src: etc/ansible/facts.d/tor.json.j2
    dest: /etc/ansible/facts.d/tor.fact
    owner: root
    group: root
    mode: "0600"
  when: tor_persistence is defined
