---
# TODO: Move settings dir to {{ volumes_root }}
- name: Create settings path if it does not exist
  file:
    path: settings/passwords
    state: directory
    mode: '0755'

- name: Copy HomelabOS config file into place
  template:
    src: "config.yml"
    dest: "{{ playbook_dir }}/settings/config.yml"

- name: Copy HomelabOS vault file into place
  template:
    src: "vault.yml"
    dest: "{{ playbook_dir }}/settings/vault.yml"

- name: Generate Ansible inventory file
  template:
    src: "inventory.j2"
    dest: "{{ playbook_dir }}/inventory"
