---
- name: Make ombi directory.
  file:
    path: "/var/homelabos/ombi"
    state: directory

- name: Copy ombi docker-compose.yml file into place.
  template:
    src: docker-compose.ombi.yml.j2
    dest: /var/homelabos/ombi/docker-compose.ombi.yml
  vars:
    tor_domain: "{{ tor_http_domain_file.stdout | default('') }}"

- name: Configure ombi systemd service.
  template: src=service.j2 dest=/etc/systemd/system/ombi.service

- name: Start ombi
  systemd:
    name: ombi
    enabled: "yes"
    daemon-reload: "yes"
    state: started
