---
- name: remove enable services.
  file:
    state: absent
    path: "{{ volumes_root }}/{{ service_item }}"
  when: confirm_remove|bool
  loop: "{{ services|flatten(levels=1) }}"
  loop_control:
    loop_var: service_item

- name: Ensure disabled services are not running
  systemd:
    name: "{{ service_item }}"
    state: stopped
    enabled: false
  when: "query and confirm_remove"
  loop: "{{ services | flatten(1) }}"
  loop_control:
    loop_var: service_item
  ignore_errors: "yes"
  vars:
    query: "not {{ service_item + '.enable' }}"

- name: remove enable services.
  file:
    state: absent
    path: "/etc/systemd/system/{{ service_item }}.service"
  when: confirm_remove|bool
  loop: "{{ services|flatten(levels=1) }}"
  loop_control:
    loop_var: service_item

- when: confirm_remove|bool
  debug:
    msg: "Package removed successfully! Go to https://{{ domain }}/ to get started."

- debug:
    msg: "Problems? File an issue at https://gitlab.com/NickBusey/HomelabOS/issues"
