---
- name: Make hubzilla directories.
  file:
    path: "{{ volumes_root }}/hubzilla/{{ item }}"
    state: directory
  with_items: ["conf", "data", "db"]

- name: Copy hubzilla docker-compose.yml file into place.
  template:
    src: docker-compose.hubzilla.yml.j2
    dest: "{{ volumes_root }}/hubzilla/docker-compose.hubzilla.yml"
  vars:
    tor_domain: "{{ tor_http_domain_file.stdout | default('') }}"

- name: Copy nginx configuration file into place.
  template:
    src: hubzilla-nginx.conf.j2
    dest: "{{ volumes_root }}/hubzilla/conf/hubzilla-nginx.conf"

- name: Configure hubzilla systemd service.
  template:
    src: service.j2
    dest: /etc/systemd/system/hubzilla.service

- name: Start hubzilla
  systemd:
    name: hubzilla
    enabled: "yes"
    daemon-reload: "yes"
    state: started
