################################### Default Configuration ############################
baseurl = "https://homelabos.com/"
languageCode = "en"
title = "HomelabOS"
theme = "vex-hugo"

#################################### Plugins ##########################################
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  URL = "https://fonts.googleapis.com/css?family=Droid+Serif:400i|Source+Sans+Pro:300,400,600,700"
  [[params.plugins.css]]
  URL = "https://fonts.googleapis.com/css?family=Josefin+Sans:300,400,600,700"
  [[params.plugins.css]]
  URL = "css/bootstrap.min.css"
  [[params.plugins.css]]
  URL = "css/themefisher-fonts.css"
  [[params.plugins.css]]
  URL = "css/owl.carousel.css"
  [[params.plugins.css]]
  URL = "css/magnific-popup.css"

  # JS Plugins
  [[params.plugins.js]]
  URL = "js/jquery-2.1.1.min.js"
  [[params.plugins.js]]
  URL = "js/bootstrap.min.js"
  [[params.plugins.js]]
  URL = "js/owl.carousel.min.js"
  [[params.plugins.js]]
  URL = "js/jquery.magnific-popup.min.js"


###################################### Navigation ######################################
[menu]
    
  [[menu.main]]
  name = "Features"
  URL = "feature"
  weight = 20
  
  [[menu.main]]
  name = "Gallery"
  URL = "gallery"
  weight = 30
  
  [[menu.main]]
  name = "Testimonial"
  URL = "testimonial"
  weight = 40

  [[menu.main]]
  name = "Community"
  URL = "community"
  weight = 50


########################### Default parameters ##########################
[params]
logo = ""
home = "Home"
# Meta data
description = "Your very own offline-first privacy-centric open-source data-center! "
author = "Themefisher"
# copyright
copyright = "Copyright 2019 &copy; [themefisher](http://www.Themefisher.com) | All right reserved."

# Preloader
[params.preloader]
enable = true
preloader = "" # use .png , .svg or .gif format