---
- name: Make homeassistant directory.
  file:
    path: "{{ volumes_root }}/homeassistant"
    state: directory

- name: Copy homeassistant docker-compose.yml file into place.
  template:
    src: docker-compose.homeassistant.yml.j2
    dest: "{{ volumes_root }}/homeassistant/docker-compose.yml"
  vars:
    tor_domain: "{{ tor_http_domain_file.stdout | default('') }}"

- name: Configure homeassistant systemd service.
  template:
    src: service.j2
    dest: /etc/systemd/system/homeassistant.service

- name: Start homeassistant
  systemd:
    name: homeassistant
    enabled: "yes"
    daemon-reload: "yes"
    state: started
