---
- name: Make bitwarden directory.
  file:
    path: "{{ volumes_root }}/bitwarden"
    state: directory

- name: Copy bitwarden docker-compose.yml file into place.
  template:
    src: docker-compose.bitwarden.yml.j2
    dest: "{{ volumes_root }}/bitwarden/docker-compose.bitwarden.yml"
  vars:
    tor_domain: "{{ tor_http_domain_file.stdout | default('') }}"


- name: Configure bitwarden systemd service.
  template:
    src: service.j2
    dest: /etc/systemd/system/bitwarden.service

- name: Start bitwarden
  systemd:
    name: bitwarden
    enabled: "yes"
    daemon-reload: "yes"
    state: started
