# These are the default settings. Copy this file to `host_vars/myserver` then in that file set the values to match your setup.

### REQUIRED ###
# These values are REQUIRED for HomelabOS to work.

# SSH accessible IP address
homelab_ip: {{ homelab_ip }}

# User name used to connect via ssh. Must have passwordless sudo.
homelab_ssh_user: {{ homelab_ssh_user }}

# Default user name to create as admin with services
default_username: {{ default_username }}

# Default storage location for service data, such as configuration data
volumes_root: {{ volumes_root | default('/var/homelabos') }}

# Default storage location for media (These are used as local directories or NAS mount points depending on configuration)
storage_dir: {{ storage_dir | default('/mnt/nas') }}

# Default Ubuntu release name to follow. Valid examples include: bionic, cosmic, disco
ubuntu_release: {{ ubuntu_release | default('bionic') }}

# Set this to true if you are deploying to an ARM infrastructure, such as a Raspberry Pi.

arm: {{ arm | default('False') }}

# This configuration dictionary sets various details of your bastion host.
# see the docs for more information about what a bastion host is and how
# the HomelabOS bastion host works.
bastion:
  # should HomelabOS utilize a bastion server?
  enabled: {{ bastion.enabled | default(False) }}
  # Bastion host main ethernet interface name
  interface: {{ bastion.interface | default("eth0") }}
  # must provide passwordless sudo
  server_ssh_user: {{ bastion.server_ssh_user | default('root') }}
  # Can be an IP or a hostname
  server_address: {{ bastion.server_address | default(False) }}
  wireguard:
    bastion_vpn_address: {{ bastion.wireguard.bastion_vpn_address | default("10.0.1.1") }}
    homelab_vpn_address: {{ bastion.wireguard.home_vpn_address | default("10.0.1.2") }}
    netmask: {{ bastion.wireguard.netmask | default("/24") }}
    port: {{ bastion.wireguard.port | default("51820") }}
    keepalive: {{ bastion.wireguard.keepalive | default("25") }}
  ports_to_forward:
    2222: 22
    80: 80
    443: 443
    25: 25
    143: 143
    587: 587
    998: 998
    4190: 4190
  # MIGRATION v0.7
  # Should HomelabOS reset the bastion server IP tables rules?
  # Enable this if you are upgrading a Tinc bastion host
  reset_iptables: {{ bastion.reset_iptables | default(False) }}
  # END MIGRATION


# Timezone of the server
common_timezone: {{ common_timezone | default('Etc/UTC') }}

# Domain that will be used to point at the server
# Must have a DNS A record of `*.yourserver.com` pointing at your server's IP.
domain: {{ domain | default('localhost') }}

# An email that is accessible outside of HomelabOS that you can receive system alerts and notices at.
# Necessary for SSL / LetsEncrypt to work.
admin_email: {{ admin_email | default('test@test.com') }}

ansible_port: {{ ansible_port | default(22) }}

# Features

# You can enable/disable different HomelabOS features here by changing False to True and vice versa.

enable_tor: {{ enable_tor | default(False) }}

# Force SSL Usage
# Only set this to true after everything is working, and https certificates have been generated.
# DEPRECATED: as of HomelabOS 0.7 this has been replaced by the individual service configs below
# https_only: {{ https_only | default(False) }}

# Services

# Enable HomelabOS documentation

enable_docs: {{ enable_docs | default(False) }}
#== PARSE ###
# You can enable/disable services individually by changing False to True and vice versa.
enable_apache2: {{ enable_apache2 | default(False) }}
enable_apple_health_influx: {{ enable_apple_health_influx | default(False) }}
enable_airsonic: {{ enable_airsonic | default(False) }}
enable_authelia: {{ enable_authelia | default(False) }}
enable_bitwarden: {{ enable_bitwarden | default(False) }}
enable_beets: {{ enable_beets | default(False) }}
enable_bookstack: {{ enable_bookstack | default(False) }}
enable_bulletnotes: {{ enable_bulletnotes | default(False) }}
enable_calibre: {{ enable_calibre | default(False) }}
enable_chowdown: {{ enable_chowdown | default(False) }}
enable_codeserver: {{ enable_codeserver | default(False) }}
enable_darksky_influx: {{ enable_darksky_influx | default(False) }}
enable_dasher: {{ enable_dasher | default(False) }}
enable_digikam: {{ enable_digikam | default(False) }}
enable_drone: {{ enable_drone | default(False) }}
enable_duplicati: {{ enable_duplicati | default(False) }}
enable_emby: {{ enable_emby | default(False) }}
enable_erpnext: {{ enable_erpnext | default(False) }}
enable_firefly_iii: {{ enable_firefly_iii | default(False) }}
enable_folding_at_home: {{ enable_folding_at_home | default(False) }}
enable_freshrss: {{ enable_freshrss | default(False) }}
enable_ghost: {{ enable_ghost | default(False) }}
enable_gitea: {{ enable_gitea | default(False) }}
enable_grafana: {{ enable_grafana | default(False) }}
enable_grocy: {{ enable_grocy | default(False) }}
enable_grownetics: {{ enable_grownetics | default(False) }}
enable_guacamole: {{ enable_guacamole | default(False) }}
enable_healthchecks: {{ enable_healthchecks | default(False) }}
enable_homeassistant: {{ enable_homeassistant | default(False) }}
enable_homebridge: {{ enable_homebridge | default(False) }}
enable_homedash: {{ enable_homedash | default(False) }}
enable_inventario: {{ enable_inventario | default(False) }}
enable_jackett: {{ enable_jackett | default(False) }}
enable_jellyfin: {{ enable_jellyfin | default(False) }}
enable_kibitzr: {{ enable_kibitzr | default(False) }}
enable_lidarr: {{ enable_lidarr | default(False) }}
enable_mailserver: {{ enable_mailserver | default(False) }}
enable_mailu: {{ enable_mailu | default(False) }}
enable_mashio: {{ enable_mashio | default(False) }}
enable_matomo: {{ enable_matomo | default(False) }}
enable_mayan: {{ enable_mayan | default(False) }}
enable_minecraft: {{ enable_minecraft | default(False) }}
enable_miniflux: {{ enable_miniflux | default(False) }}
enable_minio: {{ enable_minio | default(False) }}
enable_monicahq: {{ enable_monicahq | default(False) }}
enable_mstream: {{ enable_mstream | default(False) }}
enable_mylar: {{ enable_mylar | default(False) }}
enable_netdata: {{ enable_netdata | default(False) }}
enable_nextcloud: {{ enable_nextcloud | default(False) }}
enable_nzbget: {{ enable_nzbget | default(False) }}
enable_ombi: {{ enable_ombi | default(False) }}
enable_openldap: {{ enable_openldap | default(False) }}
enable_openvpn: {{ enable_openvpn | default(False) }}
enable_organizr: {{ enable_organizr | default(True) }}
enable_ownphotos: {{ enable_ownphotos | default(False) }}
enable_paperless: {{ enable_paperless | default(False) }}
enable_pihole: {{ enable_pihole | default(False) }}
enable_piwigo: {{ enable_piwigo | default(False) }}
enable_pixelfed: {{ enable_pixelfed | default(False) }}
enable_plex: {{ enable_plex | default(False) }} # Set Plex Claim Token below
enable_poli: {{ enable_poli | default(False) }}
enable_portainer: {{ enable_portainer | default(False) }}
enable_privatebin: {{ enable_privatebin | default(False) }}
enable_radarr: {{ enable_radarr | default(False) }}
enable_restic: {{ enable_restic | default(False) }}
enable_sabnzbd: {{ enable_sabnzbd | default(False) }}
enable_searx: {{ enable_searx | default(False) }}
enable_sickchill: {{ enable_sickchill | default(False) }}
enable_sonarr: {{ enable_sonarr | default(False) }}
enable_speedtest: {{ enable_speedtest | default(False) }}
enable_syncthing: {{ enable_syncthing | default(False) }}
enable_tautulli: {{ enable_tautulli | default(False) }}
enable_thelounge: {{ enable_thelounge | default(False) }}
enable_tick: {{ enable_tick | default(False) }}
enable_transmission: {{ enable_transmission | default(False) }}
enable_trilium: {{ enable_trilium | default(False) }}
enable_ubooquity: {{ enable_ubooquity | default(False) }}
enable_wekan: {{ enable_wekan | default(False) }}
enable_watchtower: {{ enable_watchtower | default(False) }}
enable_xfinityusageinfluxdb: {{ enable_xfinityusageinfluxdb | default(False) }}
enable_wallabag: {{ enable_wallabag | default(False) }}
enable_webvirtmgr: {{ enable_webvirtmgr | default(False) }}
enable_zulip: {{ enable_zulip | default(False) }}

### END REQUIRED ###

### OPTIONAL ### These valuse are OPTIONAL and enable extra HomelabOS functionality.

# Your DarkSky API Key. Get one at http://darksky.net/dev
darksky_key: {{ darksky_key | default() }}

# Your location
latitude: {{ latitude | default() }}
longitude: {{ longitude | default() }}

# VPN For Transmission to use for Downloads
openvpn_provider: {{ openvpn_provider | default() }}
openvpn_username: {{ openvpn_username | default() }}
openvpn_password: {{ openvpn_password | default() }}
openvpn_config: {{ openvpn_config | default() }}

# NAS Config (Docs: https://nickbusey.gitlab.io/HomelabOS/setup/installation/#nas-network-attached-storage-configuration)
nas_enable: {{ nas_enable | default(False) }}
nas_host: {{ nas_host | default() }}
nas_mount_type: {{ nas_mount_type | default() }}
nas_share_path: {{ nas_share_path | default() }}
nas_user: {{ nas_user | default(default_username) }}
nas_pass: {{ nas_pass | default() }}
nas_workgroup: {{ nas_workgroup | default() }}

# Example: 0 4 * * *
# Backup every day at 4:00 AM
s3_backup_cron: {{ s3_backup_cron | default() }}
s3_path: {{ s3_path | default() }}

# Apple Health Data Importer name: Docs: https://nickbusey.gitlab.io/HomelabOS/software/applehealth/
apple_health_nextcloud_username: {{ apple_health_nextcloud_username | default()  }}

apache2_subdomain: {{ apache2_subdomain | default('apache2') }}

# Individual per service settings

airsonic:
  https_only: {{ airsonic.https_only | default(False) }}
  auth: {{ airsonic.auth | default(False) }}

apache2:
  https_only: {{ apache2.https_only | default(False) }}
  auth: {{ apache2.auth | default(False) }}

apple_health_influx:

beets:
  https_only: {{ beets.https_only | default(False) }}
  auth: {{ beets.auth | default(False) }}

bitwarden:
  https_only: {{ bitwarden.https_only | default(False) }}
  auth: {{ bitwarden.auth | default(False) }}
  # Enable admin page
  # IMPORTANT: Activate HTTPS before enabling this feature, to avoid possible MITM attacks.
  # Reference: https://github.com/dani-garcia/bitwarden_rs/wiki/Enabling-admin-page
  token: {{ bitwarden.token | default(False) }}

bookstack:
  https_only: {{ bookstack.https_only | default(False) }}
  auth: {{ bookstack.auth | default(False) }}

bulletnotes:
  https_only: {{ bulletnotes.https_only | default(False) }}
  auth: {{ bulletnotes.auth | default(False) }}

calibre:
  https_only: {{ calibre.https_only | default(False) }}
  auth: {{ calibre.auth | default(False) }}

chowdown:
  https_only: {{ chowdown.https_only | default(False) }}
  auth: {{ chowdown.auth | default(False) }}

codeserver:
  https_only: {{ codeserver.https_only | default(False) }}
  auth: {{ codeserver.auth | default(False) }}

darksky_influx:

dasher:

digikam:
  auth: {{ digikam.auth | default(False) }}
  https_only: {{ digikam.https_only | default(False) }}

docs:
  https_only: {{ docs.https_only | default(False) }}
  auth: {{ docs.auth | default(False) }}

drone:
  https_only: {{ drone.https_only | default(False) }}
  auth: {{ drone.auth | default(False) }}

duplicati:
  https_only: {{ duplicati.https_only | default(False) }}
  auth: {{ duplicati.auth | default(False) }}

emby:
  https_only: {{ emby.https_only | default(False) }}
  auth: {{ emby.auth | default(False) }}

erpnext:
  https_only: {{ erpnext.https_only | default(False) }}
  auth: {{ erpnext.auth | default(False) }}

folding_at_home:
  username: {{ folding_at_home.username | default( default_username ) }}
  # Team HomelabOS - https://stats.foldingathome.org/team/261443
  team: {{ folding_at_home.team | default( "261443" ) }}
  # Valid values are 'light', 'medium' or 'full'
  power: {{ folding_at_home.power | default("full")}}

firefly_iii:
  https_only: {{ firefly_iii.https_only | default(False) }}
  auth: {{ firefly_iii.auth | default(False) }}

freshrss:
  https_only: {{ freshrss.https_only | default(False) }}
  auth: {{ freshrss.auth | default(False) }}

ghost:
  https_only: {{ ghost.https_only | default(False) }}
  auth: {{ ghost.auth | default(False) }}

gitea:
  https_only: {{ gitea.https_only | default(False) }}
  auth: {{ gitea.auth | default(False) }}
  use_mariadb: {{ gitea.use_mariadb | default(True) }}
  gitea_ssh_port: {{ gitea.gitea_ssh_port | default(222) }}

grafana:
  https_only: {{ grafana.https_only | default(False) }}
  auth: {{ grafana.auth | default(False) }}

grocy:
  https_only: {{ grocy.https_only | default(False) }}
  auth: {{ grocy.auth | default(False) }}

grownetics:
  https_only: {{ grownetics.https_only | default(False) }}
  auth: {{ grownetics.auth | default(False) }}

guacamole:
  https_only: {{ guacamole.https_only | default(False) }}
  auth: {{ guacamole.auth | default(False) }}

healthchecks:
  https_only: {{ healthchecks.https_only | default(False) }}
  auth: {{ healthchecks.auth | default(False) }}

homeassistant:
  https_only: {{ homeassistant.https_only | default(False) }}
  auth: {{ homeassistant.auth | default(False) }}

homebridge:
  https_only: {{ homebridge.https_only | default(False) }}
  auth: {{ homebridge.auth | default(False) }}

homedash:
  https_only: {{ homedash.https_only | default(False) }}
  auth: {{ homedash.auth | default(False) }}

inventario:
  https_only: {{ inventario.https_only | default(False) }}
  auth: {{ inventario.auth | default(False) }}

jackett:
  https_only: {{ jackett.https_only | default(False) }}
  auth: {{ jackett.auth | default(False) }}

jellyfin:
  https_only: {{ jellyfin.https_only | default(False) }}
  auth: {{ jellyfin.auth | default(False) }}

kibitzr:

lidarr:
  https_only: {{ lidarr.https_only | default(False) }}
  auth: {{ lidarr.auth | default(False) }}

mailserver:
  https_only: {{ mailserver.https_only | default(False) }}
  auth: {{ mailserver.auth | default(False) }}
  forward_to_smtp: {{ mailserver.forward_to_smtp | default(False)  }}

mashio:
  https_only: {{ mashio.https_only | default(False) }}
  auth: {{ mashio.auth | default(False) }}

matomo:
  https_only: {{ matomo.https_only | default(False) }}
  auth: {{ matomo.auth | default(False) }}

mayan:
  https_only: {{ mayan.https_only | default(False) }}
  auth: {{ mayan.auth | default(False) }}

miniflux:
  https_only: {{ miniflux.https_only | default(False) }}
  auth: {{ miniflux.auth | default(False) }}

minio:
  https_only: {{ minio.https_only | default(False) }}
  auth: {{ minio.auth | default(False) }}

monicahq:
  https_only: {{ monicahq.https_only | default(False) }}
  auth: {{ monicahq.auth | default(False) }}

mstream:
  https_only: {{ mstream.https_only | default(False) }}
  auth: {{ mstream.auth | default(False) }}

mylar:
  https_only: {{ mylar.https_only | default(False) }}
  auth: {{ mylar.auth | default(False) }}

netdata:
  https_only: {{ netdata.https_only | default(False) }}
  auth: {{ netdata.auth | default(False) }}

nextcloud:
  https_only: {{ nextcloud.https_only | default(False) }}
  auth: {{ nextcloud.auth | default(False) }}

nzbget:
  https_only: {{ nzbget.https_only | default(False) }}
  auth: {{ nzbget.auth | default(False) }}

ombi:
  https_only: {{ ombi.https_only | default(False) }}
  auth: {{ ombi.auth | default(False) }}

openldap:
  https_only: {{ openldap.https_only | default(False) }}
  auth: {{ openldap.auth | default(False) }}

openvpn:

organizr:
  https_only: {{ organizr.https_only | default(False) }}
  auth: {{ organizr.auth | default(False) }}

ownphotos:
  https_only: {{ ownphotos.https_only | default(False) }}
  auth: {{ ownphotos.auth | default(False) }}

paperless:
  https_only: {{ paperless.https_only | default(False) }}
  auth: {{ paperless.auth | default(False) }}

pihole:
  https_only: {{ pihole.https_only | default(False) }}
  auth: {{ pihole.auth | default(False) }}

piwigo:
  https_only: {{ piwigo.https_only | default(False) }}
  auth: {{ piwigo.auth | default(False) }}

pixelfed:
  https_only: {{ pixelfed.https_only | default(False) }}
  auth: {{ pixelfed.auth | default(False) }}

plex:
  https_only: {{ plex.https_only | default(False) }}
  auth: {{ plex.auth | default(False) }}

poli:
  https_only: {{ poli.https_only | default(False) }}
  auth: {{ poli.auth | default(False) }}

portainer:
  https_only: {{ portainer.https_only | default(False) }}
  auth: {{ portainer.auth | default(False) }}

privatebin:
  https_only: {{ privatebin.https_only | default(False) }}
  auth: {{ privatebin.auth | default(False) }}

sabnzbd: 
  https_only: {{ sabnzbd.https_only | default(False) }}
  auth: {{ sabnzbd.auth | default(False) }}

sickchill:
  https_only: {{ sickchill.https_only | default(False) }}
  auth: {{ sickchill.auth | default(False) }}

sonarr:
  https_only: {{ sonarr.https_only | default(False) }}
  auth: {{ sonarr.auth | default(False) }}

radarr:
  https_only: {{ radarr.https_only | default(False) }}
  auth: {{ radarr.auth | default(False) }}

restic:

speedtest:
  https_only: {{ speedtest.https_only | default(False) }}
  auth: {{ speedtest.auth | default(False) }}
  server: {{ speedtest.server | default (11441) }}

syncthing:
  https_only: {{ syncthing.https_only | default(False) }}
  auth: {{ syncthing.auth | default(False) }}

tautulli:
  https_only: {{ tautulli.https_only | default(False) }}
  auth: {{ tautulli.auth | default(False) }}

thelounge:
  https_only: {{ thelounge.https_only | default(False) }}
  auth: {{ thelounge.auth | default(False) }}

tick:
  https_only: {{ tick.https_only | default(False) }}
  auth: {{ tick.auth | default(False) }}

transmission:
  https_only: {{ transmission.https_only | default(False) }}
  auth: {{ transmission.auth | default(True) }}

trilium:
  https_only: {{ trilium.https_only | default(False) }}
  auth: {{ trilium.auth | default(False) }}

ubooquity:
  https_only: {{ ubooquity.https_only | default(False) }}
  auth: {{ ubooquity.auth | default(False) }}

wallabag:
  https_only: {{ wallabag.https_only | default(False) }}
  auth: {{ wallabag.auth | default(False) }}

webvirtmgr:
  https_only: {{ webvirtmgr.https_only | default(False) }}
  auth: {{ webvirtmgr.auth | default(False) }}

wekan:
  https_only: {{ wekan.https_only | default(False) }}
  auth: {{ wekan.auth | default(False) }}

watchtower:

xfinityusageinfluxdb:

zulip:
  https_only: {{ zulip.https_only | default(False) }}
  auth: {{ zulip.auth | default(False) }}
