vault:
  # Minio access keys
  minio_access_key: {{ vault.minio_access_key | default() }}
  minio_secret_access_key: {{ vault.minio_secret_access_key | default() }}

  # VPN For Transmission to use for Downloads
  openvpn_provider: {{ vault.openvpn_provider | default() }}
  openvpn_username: {{ vault.openvpn_username | default() }}
  openvpn_password: {{ vault.openvpn_password | default() }}
  openvpn_config: {{ vault.openvpn_config | default() }}

  # Cloud Servers
  aws:
    secret_key: {{ vault.aws.secret_key | default() }}
    access_key: {{ vault.aws.access_key | default() }}
    region: {{ vault.aws.region | default() }}

  do_access_token: {{ vault.do_access_token | default(False) }}
  do_region: {{ vault.do_region | default('nyc1') }}

  # After claiming your token at https://www.plex.tv/claim/ you will only have four minutes to run make and deploy plexinc
  plex_claim: {{ vault.plex_claim | default('CHANGE_TO_GIVEN_TOKEN') }}

  # Mapbox Api keys: Used for OwnPhotos
  mapbox_api_key: {{ vault.mapbox_api_key | default() }}

  # Restic S3 Backup Server Information name: Docs: https://nickbusey.gitlab.io/HomelabOS/setup/backups/
  s3_access_key: {{ vault.s3_access_key | default() }}
  s3_secret_key: {{ vault.s3_secret_key | default() }}
  s3_backup_password: {{ vault.s3_backup_password | default() }}

  # Home Assitant API Key
  homeassistant_api_key: {{ vault.homeassistant_api_key | default() }}

  # Xfinity Data Usage Settings
  xfinity_user: {{ vault.xfinity_user | default()  }}
  xfinity_password: {{ vault.xfinity_password | default()  }}

  # SMTP Settings
  smtp:
    host: {{ vault.smtp.host | default()  }}
    port: {{ vault.smtp.port | default()  }}
    user: {{ vault.smtp.user | default()  }}
    pass: {{ vault.smtp.pass | default()  }}
    from_email: {{ vault.smtp.from_email | default()  }}
    from_name: {{ vault.smtp.from_name | default()  }}

  traefik:
    https_only: {{ vault.traefik.https_only | default(False) }}
    domain: {{ vault.traefik.domain | default(False) }}
    subdomain: {{ vault.traefik.subdomain | default("traefik") }}
    auth: {{ vault.traefik.auth | default(False) }}
    expose_internally: {{ vault.traefik.expose_internally | default(True)  }}
    expose_externally: {{ vault.traefik.expose_externally | default(False)  }}
    # Enable sendAnonymousUsage?
    # Reference: https://docs.traefik.io/master/contributing/data-collection/
    send_anonymous_usage: {{ vault.traefik.send_anonymous_usage | default("false")  }}
    dns_challenge_provider: {{ vault.traefik.dns_challenge_provider | default(False) }}
  # use key:value pairs here to add additional environment variables to your traefik docker image.
  # for instance, if you're using a dns challenge provider place your api keys etc here.
    additional_env_vars:
      # DUMMY_KEY: DUMMY_VALUE
      CF_API_EMAIL: {{ vault.traefik.additional_env_vars.CF_API_EMAIL | default('EMAIL') }}
      CF_API_KEY: {{ vault.traefik.additional_env_vars.CF_API_KEY | default('API_KEY') }}

  authelia:
    duo:
      hostname: {{ vault.authelia.duo.hostname | default() }}
      integration_key: {{ vault.authelia.duo.integration_key | default() }}
      secret_key: {{ vault.authelia.duo.secret_key | default() }}
    # Don't change these unless you know what you're doing
    migration: {{ vault.authelia.migration | default(False) }}

  bitwarden:
    token: {{ vault.bitwarden.token | default(default_password) }}

  drone:
    gitea_id: {{ vault.drone.gitea_id | default(False) }}
    gitea_secret: {{ vault.drone.gitea_secret | default(False) }}

  duckdns:
    token: {{ vault.duckdns.token | default(False) }}

  watchtower:
    gotify_token: {{ vault.watchtower.gotify_token | default (False) }}

# These are here so the Prompts during initial setup work properly.
# SUDO password
ansible_become_password: "{{ ansible_become_password | default() }}"

# Default password to go with the default user
default_password: "{{ default_password | default() }}"
