---
- name: Make webVirtMgr directory.
  file:
    path: "/var/homelabos/webvirtmgr"
    state: directory

- name: Copy webVirtMgr docker-compose.yml file into place.
  template:
    src: docker-compose.webvirtmgr.yml.j2
    dest: /var/homelabos/webvirtmgr/docker-compose.webvirtmgr.yml
  vars:
    tor_domain: "{{ tor_http_domain_file.stdout | default('') }}"

- name: Configure webVirtMgr systemd service.
  template: src=service.j2 dest=/etc/systemd/system/webvirtmgr.service

- name: Start webVirtMgr
  systemd:
    name: webvirtmgr
    enabled: "yes"
    daemon-reload: "yes"
    state: started
